"use client";
import { useEffect, useState } from "react";
import Head from "next/head";

import styles from "../styles/Home.module.css";
 
export default function Home() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [todo, setTodo] = useState("");
  let changeHandler = (event) => {
    setTodo(event.target.value);
  };
 
  let addTodo = (event) => {
    setLoading(true);
    event.preventDefault();
    fetch("/api/add?todo=" + todo)
      .then(res => res.json())
      .then(data => {
        loadTodos();
      });
  };
 
  let removeTodo = (rtodo) => {
    setLoading(true);
    fetch("/api/remove?todo=" + rtodo)
      .then(res => res.json())
      .then(data => {
        loadTodos();
      });
  };
 
  let loadTodos = () => {
    console.log("load todos");
    fetch("/api/list", { cache: "no-store" })
      .then(res => res.json())
      .then(data => {
        setData(data);
        setLoading(false);
        console.log(data);
      });
  };
 
  useEffect(() => {
    setLoading(true);
    loadTodos();
  }, []);
 
  if (!data) return "Loading...";
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js TODO APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <main className={styles.main}>
        <div className={styles.grid}>
          <h1 className={styles.title}>
            Todo <span style={{color:"#2596be"}}> List  </span>{" "}
            
            <br />
          </h1>
        
          {loading ? (
            <a href="#" className={styles.loading}>
              <img src="/images/loading.gif"  />
            </a>
          ) : (
            <form className={styles.cardForm} onSubmit={addTodo}>
              <input
                className={styles.cardInput}
                type="text"
                name="todo"
                onChange={changeHandler}
                placeholder="I need to..."
              />
            </form>
          )}
 
          {data.map((item) => (
            <a
              key={item}
              href="#"
              onClick={() => removeTodo(item)}
              className={styles.card}
            >
              <p>{item}</p>
            </a>
          ))}
        </div>
      </main>
 
      <footer className={styles.footer}>
        
          Made with {"  "}
          <a style={{textDecoration:"underline"}} href="https://nextjs.org/" target="_blank"> Next.js</a>, 
          <a style={{textDecoration:"underline"}}href="https://upstash.com/" target="_blank"> Upstash Redis</a>,
          <a style={{textDecoration:"underline"}}href="https://vercel.com/docs/functions" target="_blank"> Vercel Functions</a>

          <a href="https://github.com/minoritydev/nextjs-serverless-todo-app/tree/master" target="_blank">
            &lt; Github /&gt;
          </a>
          
        
      </footer>
    </div>
  );
}